import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import {
      PlayCircleIcon,
      PlayIcon,
      SpeakerWaveIcon,
} from "@heroicons/react/16/solid";
import Card from "./_components/Card";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
      title: "Spotify - Clone",
      description: "Generated by create next app",
};

export default function RootLayout({
      children,
}: Readonly<{
      children: React.ReactNode;
}>) {
      return (
            <html lang="en">
                  <body className={inter.className}>
                        <div className=" flex h-screen flex-col justify-between">
                              <div className="flex min-h-[90vh] grow select-none">
                                    <Navbar />
                                    <div
                                          className="scrollbar-hide m-2 ml-0 w-full overflow-scroll rounded-md p-4 pt-2"
                                          style={{
                                                background:
                                                      "linear-gradient(to bottom, #3e1a1a, #121212 30%)",
                                          }}
                                    >
                                          {children}
                                    </div>
                              </div>
                              <div className="flex w-full justify-between p-4 pt-2">
                                    <Card type="small" />
                                    <div>
                                          <PlayCircleIcon className="size-12" />
                                    </div>
                                    <div className="flex items-center">
                                          <SpeakerWaveIcon className="size-5 fill-none stroke-white opacity-70" />
                                    </div>
                              </div>
                        </div>
                  </body>
            </html>
      );
}
