import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import {
  PlayCircleIcon,
  PlayIcon,
  SpeakerWaveIcon,
} from "@heroicons/react/16/solid";
import Card from "./_components/Card";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spotify - Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const date = new Date();
  const year = date.getFullYear();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" flex h-screen flex-col justify-between">
          <div className="flex min-h-[90vh] grow select-none">
            <Navbar />
            <div
              className="scrollbar-hide relative m-2 ml-0 flex w-full flex-col justify-between overflow-scroll rounded-md p-4 pt-2"
              style={{
                background: "linear-gradient(to bottom, #3e1a1a, #121212 30%)",
              }}
            >
              <div>{children}</div>
              <div className="mt-20">
                <div className="flex grow flex-wrap justify-between gap-y-12">
                  <ul className="flex flex-col gap-2 pe-24 text-sm">
                    <span className="font-bold">Company</span>
                    <li className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      About
                    </li>
                    <li className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      Jobs
                    </li>
                    <li className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      For the Record
                    </li>
                  </ul>
                  <ul className="flex flex-col gap-2 pe-24 text-sm">
                    <span className="font-bold">Communities</span>
                    <li className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      For Artists
                    </li>
                    <li className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      Developers
                    </li>
                    <li className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      Advertising
                    </li>
                    <li className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      Investors
                    </li>
                    <li className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      Vendors
                    </li>
                  </ul>
                  <ul className="flex flex-col gap-2 pe-24 text-sm">
                    <span className="font-bold">Useful links</span>
                    <li className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      Support
                    </li>
                    <li className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      Free Mobile App
                    </li>
                  </ul>
                  <ul className="flex flex-col gap-2 pe-24 text-sm">
                    <span className="font-bold">Spotify Plans</span>
                    <li className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      Premium Individual
                    </li>
                    <li className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      Premium Duo
                    </li>
                    <li className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      Premium Family
                    </li>
                    <li className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      Premium Student
                    </li>
                    <li className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      Spotify Free
                    </li>
                  </ul>
                  <div className="flex items-center gap-x-4">
                    <div className="size-9 rounded-full bg-white opacity-20"></div>
                    <div className="size-9 rounded-full bg-white opacity-20"></div>
                    <div className="size-9 rounded-full bg-white opacity-20"></div>
                  </div>
                </div>
                <div className="mt-10 flex w-full shrink-0 items-center flex-wrap justify-between border-t gap-y-4 border-[#ffffff20] py-10">
                  <div className="flex me-16 gap-x-4 text-xs">
                    <p className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      Legal
                    </p>
                    <p className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      Safety & Privacy Center
                    </p>
                    <p className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      Privacy Policy
                    </p>
                    <p className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      Cookies
                    </p>
                    <p className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      About Ads
                    </p>
                    <p className="cursor-pointer opacity-70 transition-all hover:opacity-100">
                      Accessibility
                    </p>
                  </div>
                  <p className="text-xs opacity-70">{year} Spotify AB</p>
                </div>
              </div>
            </div>
          </div>
          <div className="flex w-full justify-between p-4 pt-2">
            <Card type="small" />
            <div>
              <PlayCircleIcon className="size-12" />
            </div>
            <div className="flex items-center">
              <SpeakerWaveIcon className="size-5 fill-none stroke-white opacity-70" />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
