import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="flex select-none">
    <Navbar/>
    <div className="w-full m-2 ml-0 rounded-md bg-gradient-to-b from-red-600 to-[#121212]">
        {children}
    </div>
    </div>
        </body>
    </html>
  );
}
